-- GENERATED by bin/gen-lua-data.mjs from src/model.js — do not edit by hand.
-- Character/talent/buff DATA for the forward model (engine/Model.lua). The aggregate logic is
-- hand-ported there (parity-checked). Regenerate: npm run gen-lua (pre-commit re-runs it on changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.CharacterData = D

-- L70 Blood Elf Paladin race/class base intercepts (no gear/talents/buffs).
D.CHARACTER = {
  baseAgility = 79,
  baseStrength = 123,
  baseIntellect = 87,
  baseStamina = 122,
  baseDodgePct = 0.649,
  baseParryPct = 5,
  baseBlockPct = 5,
  agilityPerDodgePct = 25,
  armorPerAgility = 2,
  baseHealth = 3377,
  hpPerStamina = 10,
}

-- Default Avenger's Shield (0/43/18) talent modifiers; overridden live by talentsFromRanks.
D.TALENTS = {
  anticipationDefenseSkill = 20,
  deflectionParryPct = 5,
  toughnessItemArmorMult = 1.1,
  staminaMult = 1.16,
  combatExpertise = 5,
  precisionSpellHitPct = 3,
  precisionMeleeHitPct = 3,
  impRighteousFuryDR = 0.06,
}

-- Party/raid buffs: Kings is a +10% primary multiplier (after flats); MotW is flat +14 each.
D.BUFFS = {
  kingsMult = 1.1,
  markOfTheWild = {
    stamina = 14,
    strength = 14,
    agility = 14,
    intellect = 14,
  },
}

-- The stat keys summed from gear.
D.STAT_KEYS = { "stamina", "strength", "agility", "intellect", "defenseRating", "dodgeRating", "parryRating", "blockRating", "blockValue", "spellDamage", "hitRating", "expertiseRating", "spellHitRating", "spellCritRating", "resilienceRating", "armor" }

return D
