-- GENERATED by bin/gen-lua-data.mjs from src/constants.js — do not edit by hand.
-- Single source of truth for the in-game engine's DATA; the website (src/constants.js) is authoritative.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when constants change).
-- The helper FORMULAS below (ARMOR_CONST/RESIST_DENOM/crushTargetFor/crushSafeTargetFor) are hand-ported
-- logic, guarded by the Lua parity harness (test/lua/eval_parity.lua), not generated from data.

local ADDON, ns = ...
ns.engine = ns.engine or {}
local C = {}
ns.engine.Constants = C

-- --- Rating conversions (guide: #stat-conversions table) ---
-- "Rating per 1%" except defense/expertise which are per skill point.
C.RATING = {
  defensePerSkill = 2.3654, -- defense rating per 1 defense skill
  meleeHitPer1 = 15.77,     -- melee hit rating per 1%
  spellHitPer1 = 12.62,     -- spell hit rating per 1%
  expertisePer1 = 3.9423,   -- expertise rating per 1 expertise
  dodgePer1 = 18.92,        -- dodge rating per 1%
  parryPer1 = 23.65,        -- parry rating per 1%
  blockPer1 = 7.88,         -- block rating per 1%
  critPer1 = 22.08,         -- crit rating per 1%
  hastePer1 = 15.77,        -- haste rating per 1%
  resiliencePer1 = 39.42,   -- resilience rating per 1% crit reduction
}

-- --- Character / boss baselines (guide: #combat-table, #block-mechanics) ---
C.BASE = {
  playerLevel = 70,
  baseDefenseSkill = 350,        -- 5 x level
  baseMissChance = 5,            -- % melee miss vs target (guide profile baseline)
  defenseBenefitPerSkill = 0.04, -- % per defense skill to dodge/parry/block/miss/crit-avoid
  raidBossLevel = 73,
  heroicBossLevel = 72,
  bossCritVsPlayer = 5.6,        -- % crit a level 73 raid boss has on a level 70 (guide: 1531)
  heroicBossCritVsPlayer = 5.4,  -- % crit a level 72 heroic boss has on a level 70
}

-- --- Hard caps / thresholds (guide: #stat-conversions, #combat-table) ---
C.CAPS = {
  defenseSkillRaid = 490,        -- crit immunity vs level 73 (guide: 1527-1534)
  defenseSkillHeroic = 485,      -- crit immunity vs level 72
  uncrushableCombined = 102.4,   -- miss+dodge+parry+block >= this => no crushing (guide: 1566)
  shearAvoidanceTarget = 101.8,  -- Illidan Shear (no miss): dodge+parry+block(+HS) >= this = avoided
  uncrushableSafetyMargin = 0.3, -- certification requires this far OVER the cap (ratings-vs-sheet gap; see crushSafeTargetFor)
  sunwellHitReduction = 5,
  sunwellDodgeReduction = 20,
  spellHitCapPct = 17,           -- vs raid boss (guide table)
  meleeHitCapPct = 9,            -- vs raid boss (6% with 3/3 Precision)
  expertiseSoftCap = 26,         -- eliminates boss dodge
}

-- --- Threat amplifiers (guide: #threat-system) ---
C.THREAT = {
  righteousFury = 1.9,             -- 3/3 Improved Righteous Fury (guide: 845)
  holyShieldActive = 30,           -- +30% block chance while Holy Shield is up (guide: 1552)
  justicar2pcSeal = 1.1,           -- +10% SoR/SoV/SoC seal damage (guide: 633)
  justicar4pcHolyShield = 15,      -- +15 flat per Holy Shield block (guide: 634)
  crystalforge2pcRetAura = 15,     -- +15 Retribution Aura damage per hit (T5 2pc)
  crystalforge4pcBlockValue = 100, -- +100 block value for 6s after Holy Shield (T5 4pc)
  improvedHolyShieldDmg = 1.2,     -- 2/2 Improved Holy Shield damage multiplier (guide: 878)
}

-- Crit multipliers by school (guide: seal crit mechanics table, 1256-1262)
C.CRIT_MULT = {
  spell = 1.5,
  melee = 2,
}

C.RESIST_MAX_MITIGATION = 0.75

-- --- Armor mitigation (standard TBC formula; attacker-level dependent) ---
-- DR = Armor / (Armor + (467.5 * attackerLevel - 22167.5)), capped at 75%. = 11960 at level 73.
function C.ARMOR_CONST(attackerLevel)
  attackerLevel = attackerLevel or C.BASE.raidBossLevel
  return 467.5 * attackerLevel - 22167.5
end

-- --- Resistance mitigation ---
-- Average mitigation vs a caster = Resistance / (5 * casterLevel) * 0.75, capped 75%.
-- At level 73: 5*73 = 365 => 365 res = 75% (cap); 244 res ~= 50%.
function C.RESIST_DENOM(casterLevel)
  casterLevel = casterLevel or C.BASE.raidBossLevel
  return 5 * casterLevel
end

-- --- Uncrushable targets (mirror src/constants.js) ---
-- crushTargetFor = the SOLVER's target (raw crush cap, or Illidan's 101.8% Shear target, or an override).
-- crushSafeTargetFor = that PLUS a safety margin, used to CERTIFY (the reported legal flag + the Optimize
-- card ✓). The optimizer computes avoidance from summed RATINGS while the Live readout reads the game
-- sheet's exact %s (GetDodgeChance/etc.); the two differ ~0.1%, so a set that clears the raw cap can read
-- crushable once equipped. Certifying against the margin prevents that. The Live readout's own uncrushable
-- flag (Evaluate.lua) stays on the raw 102.4/101.8 caps — the true in-game boundary.
function C.crushTargetFor(enc, override)
  local base = override
  if base == nil then base = (enc == "illidan") and C.CAPS.shearAvoidanceTarget or C.CAPS.uncrushableCombined end
  return base
end
function C.crushSafeTargetFor(enc, override)
  return C.crushTargetFor(enc, override) + C.CAPS.uncrushableSafetyMargin
end

return C
