-- GENERATED by bin/gen-lua-data.mjs from src/librams.js — do not edit by hand.
-- Modeled libram stats (engine/Librams.lua); libramStats logic is hand-ported there.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when the source changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.LibramsData = D

-- Each: ids (canonical) + nameMatch (lowercase literal substrings) -> effective stat override.
D.LIBRAMS = {
  {
    ids = {
      29388,
    },
    nameMatch = {
      "libram of repentance",
    },
    stats = {
      blockRating = 42,
    },
  },
  {
    ids = {
      32368,
    },
    nameMatch = {
      "libram of eternal rest",
      "libram of the eternal rest",
    },
    stats = {
      spellDamage = 35,
    },
  },
}

return D
