-- GENERATED by bin/gen-lua-data.mjs from src/procs.js — do not edit by hand.
-- Modeled proc-trinket stats (engine/Procs.lua); procStats logic is hand-ported there.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when the source changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.ProcsData = D

-- Each: ids (canonical) + nameMatch (lowercase literal substrings) -> ADDITIVE effective stats.
D.PROCS = {
  {
    ids = {
      30447,
    },
    nameMatch = {
      "tome of fiery redemption",
    },
    stats = {
      spellDamage = 66,
    },
  },
}

return D
