-- GENERATED by bin/gen-lua-data.mjs from src/professions.js — do not edit by hand.
-- Profession perks (engine/Professions.lua); professionPerks logic is hand-ported there.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when the source changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.ProfessionsData = D

-- profession -> gear-relevant perks (extraSockets / jcGems / ringEnchant / ...).
D.PROFESSIONS = {
  Blacksmithing = {
    extraSockets = {
      hands = 1,
      wrist = 1,
    },
  },
  Jewelcrafting = {
    jcGems = true,
  },
  Enchanting = {
    ringEnchant = true,
  },
  Leatherworking = {
    bracerFurLining = true,
  },
  Engineering = {
    tinkers = true,
  },
  Tailoring = {},
  Alchemy = {
    mixology = true,
  },
  Mining = {},
  Skinning = {},
  Herbalism = {},
}

-- All profession names (for UI / validation).
D.PROFESSION_NAMES = {
  "Blacksmithing",
  "Jewelcrafting",
  "Enchanting",
  "Leatherworking",
  "Engineering",
  "Tailoring",
  "Alchemy",
  "Mining",
  "Skinning",
  "Herbalism",
}

return D
