-- GENERATED by bin/gen-lua-data.mjs from src/scrolls.js — do not edit by hand.
-- Consumable scroll stats (engine/Scrolls.lua); scrollStats logic is hand-ported there.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when the source changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.ScrollsData = D

-- key -> { name, stat, value, flat? }. flat armor bypasses Toughness; primaries ride the buff block.
D.SCROLLS = {
  agility = {
    name = "Scroll of Agility V",
    stat = "agility",
    value = 20,
  },
  strength = {
    name = "Scroll of Strength V",
    stat = "strength",
    value = 20,
  },
  intellect = {
    name = "Scroll of Intellect V",
    stat = "intellect",
    value = 20,
  },
  protection = {
    name = "Scroll of Protection V",
    stat = "armor",
    value = 301,
    flat = true,
  },
}

return D
