-- GENERATED by bin/gen-lua-data.mjs from src/sets.js — do not edit by hand.
-- Tier set data (engine/Sets.lua); setCounts/setBonusStats logic is hand-ported there.
-- Regenerate: npm run gen-lua   (the pre-commit hook re-runs it when the source changes).

local ADDON, ns = ...
ns.engine = ns.engine or {}
local D = {}
ns.engine.SetsData = D

-- itemId -> tier set name (Justicar = T4, Crystalforge = T5).
D.SET_DB = {
  [29066] = "Justicar",
  [29067] = "Justicar",
  [29068] = "Justicar",
  [29069] = "Justicar",
  [29070] = "Justicar",
  [30121] = "Crystalforge",
  [30123] = "Crystalforge",
  [30124] = "Crystalforge",
  [30125] = "Crystalforge",
  [30126] = "Crystalforge",
}

-- Set bonus -> equivalent flat-stat bundle (scored by the goal weights like any stat).
D.SET_BONUS_STATS = {
  justicar2pc = {
    spellDamage = 20,
  },
  justicar4pc = {
    spellDamage = 15,
  },
  crystalforge2pc = {
    spellDamage = 12,
  },
  crystalforge4pc = {
    blockValue = 100,
  },
}

return D
