// Stat blocks for every item in the curated BiS lists (web/bis.js), so a BiS item you DON'T own
// can be "equipped" into the sim as a planning aid ("pretend I own this"). Generated from the
// same Wowhead pages as bis.js (jsonequip), 2026-06-30. Stats use the engine's internal keys;
// sockets are colour counts (socket bonus is omitted — Wowhead encodes it as an unresolved
// enchant id, so a planned item just isn't credited its socket bonus). Used only when you
// explicitly add a missing BiS item; the optimizer still never auto-pulls from this DB.
export const BIS_ITEM_DB = {
  23538: { name: 'Bracers of the Green Fortress', slot: 'wrist', stats: { armor: 581, defenseRating: 17, dodgeRating: 10, stamina: 39 } },
  23836: { name: 'Goblin Rocket Launcher', slot: 'trinket', stats: { stamina: 45 } },
  27529: { name: 'Figurine of the Colossus', slot: 'trinket', stats: { blockRating: 32 } },
  27702: { name: 'Gladiator\'s Lamellar Chestpiece', slot: 'chest', stats: { armor: 1547, intellect: 25, resilienceRating: 27, spellCritRating: 30, spellDamage: 20, stamina: 51 }, sockets: { red: 2, yellow: 1 } },
  27705: { name: 'Gladiator\'s Lamellar Legguards', slot: 'legs', stats: { armor: 1353, intellect: 21, resilienceRating: 32, spellCritRating: 32, spellDamage: 37, stamina: 57 } },
  27706: { name: 'Gladiator\'s Lamellar Shoulders', slot: 'shoulder', stats: { armor: 1160, intellect: 18, resilienceRating: 21, spellCritRating: 24, spellDamage: 19, stamina: 34 }, sockets: { red: 1, yellow: 1 } },
  27804: { name: 'Devilshark Cape', slot: 'back', stats: { armor: 78, blockValue: 29, defenseRating: 20, dodgeRating: 18, stamina: 22 } },
  27891: { name: 'Adamantine Figurine', slot: 'trinket', stats: { defenseRating: 32 } },
  27917: { name: 'Libram of the Eternal Rest', slot: 'relic', stats: {  } },
  28245: { name: 'Pendant of Dominance', slot: 'neck', stats: { intellect: 12, resilienceRating: 16, spellDamage: 26, stamina: 31 }, sockets: { yellow: 1 } },
  28358: { name: 'Gladiator\'s Shield Wall', slot: 'offhand', stats: { armor: 5197, blockValue: 134, resilienceRating: 29, stamina: 45 } },
  28407: { name: 'Elementium Band of the Sentry', slot: 'ring', stats: { defenseRating: 20, dodgeRating: 19, stamina: 24 } },
  28516: { name: 'Barbed Choker of Discipline', slot: 'neck', stats: { defenseRating: 16, dodgeRating: 21, stamina: 39 } },
  28518: { name: 'Iron Gauntlets of the Maiden', slot: 'hands', stats: { armor: 906, blockValue: 38, blockRating: 17, defenseRating: 16, stamina: 39 }, sockets: { red: 1, yellow: 1 } },
  28528: { name: 'Moroes\' Lucky Pocket Watch', slot: 'trinket', stats: { dodgeRating: 38 } },
  28530: { name: 'Brooch of Unquenchable Fury', slot: 'neck', stats: { intellect: 21, spellDamage: 26, spellHitRating: 15, stamina: 24 } },
  28566: { name: 'Crimson Girdle of the Indomitable', slot: 'waist', stats: { armor: 816, blockRating: 20, defenseRating: 24, stamina: 36, strength: 16 }, sockets: { red: 1, yellow: 1 } },
  28593: { name: 'Eternium Greathelm', slot: 'head', stats: { armor: 1178, defenseRating: 34, stamina: 48, strength: 31 }, sockets: { red: 1, yellow: 1, blue: 1 } },
  28597: { name: 'Panzar\'Thar Breastplate', slot: 'chest', stats: { armor: 1450, blockValue: 39, blockRating: 24, defenseRating: 26, stamina: 51 }, sockets: { yellow: 1, blue: 2 } },
  28606: { name: 'Shield of Impenetrable Darkness', slot: 'offhand', stats: { armor: 4872, blockValue: 155, defenseRating: 22, stamina: 33 } },
  28621: { name: 'Wrynn Dynasty Greaves', slot: 'legs', stats: { armor: 1269, defenseRating: 27, dodgeRating: 29, stamina: 48, strength: 24 }, sockets: { red: 1, yellow: 2 } },
  28641: { name: 'General\'s Lamellar Belt', slot: 'waist', stats: { armor: 870, intellect: 23, resilienceRating: 24, spellCritRating: 23, spellDamage: 28, stamina: 34 } },
  28642: { name: 'General\'s Lamellar Greaves', slot: 'feet', stats: { armor: 1063, intellect: 23, resilienceRating: 24, spellCritRating: 23, spellDamage: 28, stamina: 34 } },
  28643: { name: 'General\'s Lamellar Bracers', slot: 'wrist', stats: { armor: 624, intellect: 12, resilienceRating: 13, spellCritRating: 14, spellDamage: 20, stamina: 22 }, sockets: { yellow: 1 } },
  28660: { name: 'Gilded Thorium Cloak', slot: 'back', stats: { armor: 385, defenseRating: 24, stamina: 30 } },
  28743: { name: 'Mantle of Abrahmis', slot: 'shoulder', stats: { armor: 1087, defenseRating: 23, stamina: 43, strength: 21 }, sockets: { red: 1, yellow: 1 } },
  28766: { name: 'Ruby Drape of the Mysticant', slot: 'back', stats: { armor: 105, intellect: 21, spellDamage: 30, spellHitRating: 18, stamina: 22 } },
  28802: { name: 'Bloodmaw Magus-Blade', slot: 'weapon', stats: { intellect: 15, spellCritRating: 25, spellDamage: 203, stamina: 16 } },
  28825: { name: 'Aldori Legacy Defender', slot: 'offhand', stats: { armor: 5279, blockValue: 137, defenseRating: 19, hitRating: 15, stamina: 39 }, sockets: { blue: 1 } },
  29066: { name: 'Justicar Chestguard', slot: 'chest', stats: { armor: 1510, blockRating: 23, defenseRating: 23, intellect: 30, spellDamage: 27, stamina: 48 }, sockets: { red: 1, blue: 1, yellow: 1 } },
  29067: { name: 'Justicar Handguards', slot: 'hands', stats: { armor: 944, blockValue: 35, defenseRating: 23, intellect: 24, spellDamage: 27, stamina: 34 } },
  29068: { name: 'Justicar Faceguard', slot: 'head', stats: { armor: 1227, defenseRating: 29, dodgeRating: 24, intellect: 24, spellDamage: 27, stamina: 43 }, sockets: { yellow: 1, meta: 1 } },
  29069: { name: 'Justicar Legguards', slot: 'legs', stats: { armor: 1322, defenseRating: 31, intellect: 31, parryRating: 31, spellDamage: 36, stamina: 46 } },
  29070: { name: 'Justicar Shoulderguards', slot: 'shoulder', stats: { armor: 1133, blockValue: 27, blockRating: 17, defenseRating: 15, intellect: 14, spellDamage: 26, stamina: 37 }, sockets: { blue: 1, yellow: 1 } },
  29172: { name: 'Ashyen\'s Gift', slot: 'ring', stats: { spellDamage: 23, spellHitRating: 21, stamina: 30 } },
  29252: { name: 'Bracers of Dignity', slot: 'wrist', stats: { armor: 608, defenseRating: 21, intellect: 12, spellDamage: 19, stamina: 30 } },
  29253: { name: 'Girdle of Valorous Deeds', slot: 'waist', stats: { armor: 782, blockRating: 16, defenseRating: 24, intellect: 22, spellDamage: 20, stamina: 37 } },
  29254: { name: 'Boots of the Righteous Path', slot: 'feet', stats: { armor: 955, defenseRating: 23, intellect: 26, spellDamage: 28, stamina: 34 } },
  29279: { name: 'Violet Signet of the Great Protector', slot: 'ring', stats: { armor: 392, defenseRating: 19, stamina: 37 } },
  29388: { name: 'Libram of Repentance', slot: 'relic', stats: {  } },
  29925: { name: 'Phoenix-Wing Cloak', slot: 'back', stats: { armor: 108, defenseRating: 22, dodgeRating: 27, stamina: 37 } },
  29998: { name: 'Royal Gauntlets of Silvermoon', slot: 'hands', stats: { armor: 1080, defenseRating: 24, dodgeRating: 32, stamina: 57 }, sockets: { yellow: 1, blue: 1 } },
  30007: { name: 'The Darkener\'s Grasp', slot: 'neck', stats: { blockRating: 14, defenseRating: 27, dodgeRating: 23, stamina: 40 } },
  30008: { name: 'Pendant of the Lost Ages', slot: 'neck', stats: { intellect: 17, spellDamage: 36, stamina: 27 } },
  30028: { name: 'Seventh Ring of the Tirisfalen', slot: 'ring', stats: { blockValue: 24, blockRating: 24, defenseRating: 17, stamina: 37 } },
  30033: { name: 'Boots of the Protector', slot: 'feet', stats: { armor: 1105, blockRating: 17, defenseRating: 26, intellect: 22, spellDamage: 27, stamina: 48 } },
  30034: { name: 'Belt of the Guardian', slot: 'waist', stats: { armor: 904, blockValue: 33, defenseRating: 19, intellect: 13, spellDamage: 21, stamina: 48 }, sockets: { red: 1, yellow: 1 } },
  30083: { name: 'Ring of Sundered Souls', slot: 'ring', stats: { defenseRating: 18, dodgeRating: 25, stamina: 45 } },
  30095: { name: 'Fang of the Leviathan', slot: 'weapon', stats: { intellect: 20, spellCritRating: 21, spellDamage: 221, stamina: 28 } },
  30096: { name: 'Girdle of the Invulnerable', slot: 'waist', stats: { armor: 904, defenseRating: 22, dodgeRating: 19, parryRating: 29, stamina: 37 }, sockets: { red: 1, blue: 1 } },
  30123: { name: 'Crystalforge Chestguard', slot: 'chest', stats: { armor: 1668, blockValue: 51, defenseRating: 28, intellect: 27, spellDamage: 32, stamina: 55 }, sockets: { red: 1, yellow: 2 } },
  30124: { name: 'Crystalforge Handguards', slot: 'hands', stats: { armor: 1042, blockValue: 30, blockRating: 22, defenseRating: 27, intellect: 21, spellDamage: 29, stamina: 40 } },
  30125: { name: 'Crystalforge Faceguard', slot: 'head', stats: { armor: 1355, blockValue: 40, blockRating: 19, defenseRating: 28, intellect: 28, spellDamage: 36, stamina: 48 }, sockets: { red: 1, meta: 1 } },
  30126: { name: 'Crystalforge Legguards', slot: 'legs', stats: { armor: 1459, blockValue: 35, blockRating: 25, defenseRating: 35, intellect: 27, spellDamage: 41, stamina: 54 }, sockets: { yellow: 1 } },
  30127: { name: 'Crystalforge Shoulderguards', slot: 'shoulder', stats: { armor: 1251, defenseRating: 26, intellect: 26, parryRating: 19, spellDamage: 22, stamina: 38 }, sockets: { red: 2 } },
  30447: { name: 'Tome of Fiery Redemption', slot: 'trinket', stats: {  } },
  30641: { name: 'Boots of Elusion', slot: 'feet', stats: { armor: 997, defenseRating: 23, dodgeRating: 38, stamina: 34 } },
  30741: { name: 'Topaz-Studded Battlegrips', slot: 'hands', stats: { armor: 944, defenseRating: 31, stamina: 49 }, sockets: { yellow: 1, blue: 1 } },
  30832: { name: 'Gavel of Unearthed Secrets', slot: 'weapon', stats: { intellect: 16, spellCritRating: 15, spellDamage: 159, stamina: 24 } },
  30889: { name: 'Kaz\'rogal\'s Hardened Heart', slot: 'offhand', stats: { armor: 5930, blockValue: 160, defenseRating: 28, hitRating: 21, stamina: 43 }, sockets: { yellow: 1 } },
  30894: { name: 'Blue Suede Shoes', slot: 'feet', stats: { armor: 162, intellect: 32, spellDamage: 56, spellHitRating: 18, stamina: 37 } },
  30896: { name: 'Glory of the Defender', slot: 'chest', stats: { armor: 1765, defenseRating: 35, dodgeRating: 51, hitRating: 34, stamina: 75 } },
  30909: { name: 'Antonidas\'s Aegis of Rapt Concentration', slot: 'offhand', stats: { armor: 6336, blockValue: 174, intellect: 20, spellCritRating: 20, spellDamage: 42, stamina: 28 } },
  30910: { name: 'Tempest of Chaos', slot: 'weapon', stats: { intellect: 22, spellCritRating: 24, spellDamage: 259, spellHitRating: 17, stamina: 30 } },
  30985: { name: 'Lightbringer Handguards', slot: 'hands', stats: { armor: 1141, defenseRating: 30, dodgeRating: 22, intellect: 28, parryRating: 30, spellDamage: 34, stamina: 44 }, sockets: { red: 1 } },
  30987: { name: 'Lightbringer Faceguard', slot: 'head', stats: { armor: 1483, defenseRating: 28, dodgeRating: 37, intellect: 27, spellDamage: 43, stamina: 67 }, sockets: { yellow: 1, meta: 1 } },
  30991: { name: 'Lightbringer Chestguard', slot: 'chest', stats: { armor: 1825, blockValue: 47, blockRating: 23, defenseRating: 31, intellect: 22, spellDamage: 39, stamina: 69 }, sockets: { red: 2, yellow: 1 } },
  30995: { name: 'Lightbringer Legguards', slot: 'legs', stats: { armor: 1597, defenseRating: 37, dodgeRating: 37, intellect: 31, spellDamage: 46, stamina: 69 }, sockets: { yellow: 1 } },
  30998: { name: 'Lightbringer Shoulderguards', slot: 'shoulder', stats: { armor: 1369, defenseRating: 25, dodgeRating: 23, intellect: 24, spellDamage: 27, stamina: 50 }, sockets: { yellow: 2 } },
  31858: { name: 'Darkmoon Card: Vengeance', slot: 'trinket', stats: { stamina: 51 } },
  31859: { name: 'Darkmoon Card: Madness', slot: 'trinket', stats: { stamina: 51 } },
  32045: { name: 'Merciless Gladiator\'s Shield Wall', slot: 'offhand', stats: { armor: 5727, blockValue: 152, resilienceRating: 31, stamina: 48 } },
  32083: { name: 'Faceguard of Determination', slot: 'head', stats: { armor: 1129, blockRating: 24, defenseRating: 32, dodgeRating: 24, stamina: 36 }, sockets: { blue: 1, meta: 1 } },
  32232: { name: 'Eternium Shell Bracers', slot: 'wrist', stats: { armor: 772, defenseRating: 24, dodgeRating: 26, stamina: 52 } },
  32245: { name: 'Tide-stomper\'s Greaves', slot: 'feet', stats: { armor: 1213, defenseRating: 19, dodgeRating: 29, spellDamage: 30, stamina: 56 }, sockets: { red: 1, yellow: 1 } },
  32250: { name: 'Pauldrons of Abyssal Fury', slot: 'shoulder', stats: { armor: 1324, defenseRating: 28, dodgeRating: 36, stamina: 72 } },
  32261: { name: 'Band of the Abyssal Lord', slot: 'ring', stats: { defenseRating: 27, hitRating: 21, stamina: 53 } },
  32263: { name: 'Praetorian\'s Legguards', slot: 'legs', stats: { armor: 1544, dodgeRating: 35, hitRating: 18, parryRating: 43, stamina: 75 }, sockets: { yellow: 2, red: 1 } },
  32267: { name: 'Boots of the Resilient', slot: 'feet', stats: { armor: 1105, blockRating: 25, defenseRating: 25, stamina: 51 }, sockets: { red: 1, yellow: 1 } },
  32279: { name: 'The Seeker\'s Wristguards', slot: 'wrist', stats: { armor: 772, blockRating: 28, defenseRating: 21, spellDamage: 22, stamina: 43 } },
  32333: { name: 'Girdle of Stability', slot: 'waist', stats: { armor: 993, blockValue: 56, defenseRating: 19, dodgeRating: 18, stamina: 56 }, sockets: { red: 1, yellow: 1 } },
  32342: { name: 'Girdle of Mighty Resolve', slot: 'waist', stats: { armor: 993, blockValue: 38, blockRating: 25, defenseRating: 26, spellDamage: 30, stamina: 56 }, sockets: { yellow: 1, blue: 1 } },
  32362: { name: 'Pendant of Titans', slot: 'neck', stats: { defenseRating: 21, dodgeRating: 25, hitRating: 20, stamina: 43 } },
  32368: { name: 'Tome of the Lightbringer', slot: 'relic', stats: {  } },
  32375: { name: 'Bulwark of Azzinoth', slot: 'offhand', stats: { armor: 6336, blockValue: 174, defenseRating: 29, stamina: 60 } },
  32450: { name: 'Gladiator\'s Gavel', slot: 'weapon', stats: { intellect: 18, resilienceRating: 18, spellDamage: 199, stamina: 28 } },
  32473: { name: 'Tankatronic Goggles', slot: 'head', stats: { armor: 1296, defenseRating: 38, dodgeRating: 22, hitRating: 13, stamina: 67 }, sockets: { meta: 1, yellow: 1 } },
  32515: { name: 'Wristguards of Determination', slot: 'wrist', stats: { armor: 703, blockRating: 13, defenseRating: 24, dodgeRating: 19, stamina: 37 } },
  32521: { name: 'Faceplate of the Impenetrable', slot: 'head', stats: { armor: 1532, blockValue: 45, blockRating: 29, defenseRating: 30, dodgeRating: 38, stamina: 82 }, sockets: { meta: 1, red: 1 } },
  32963: { name: 'Merciless Gladiator\'s Gavel', slot: 'weapon', stats: { intellect: 18, resilienceRating: 18, spellDamage: 225, spellHitRating: 15, stamina: 27 } },
  33054: { name: 'The Seal of Danzalar', slot: 'ring', stats: { armor: 295, resilienceRating: 21, spellDamage: 25, stamina: 33 } },
  33313: { name: 'Merciless Gladiator\'s Barrier', slot: 'offhand', stats: { armor: 5727, blockValue: 152, intellect: 19, resilienceRating: 27, spellDamage: 33, stamina: 27 } },
  33421: { name: 'Battleworn Tuskguard', slot: 'head', stats: { armor: 1355, blockValue: 51, defenseRating: 40, dodgeRating: 23, stamina: 60 }, sockets: { red: 1, yellow: 1, blue: 1 } },
  33473: { name: 'Chestguard of the Warlord', slot: 'chest', stats: { armor: 1668, defenseRating: 27, dodgeRating: 40, hitRating: 26, stamina: 60 }, sockets: { yellow: 1, red: 1, blue: 1 } },
  33481: { name: 'Pauldrons of Stone Resolve', slot: 'shoulder', stats: { armor: 1206, blockValue: 30, blockRating: 28, defenseRating: 20, stamina: 43 }, sockets: { blue: 2 } },
  33504: { name: 'Libram of Divine Purpose', slot: 'relic', stats: {  } },
  33515: { name: 'Unwavering Legguards', slot: 'legs', stats: { armor: 1406, blockValue: 59, blockRating: 30, defenseRating: 22, stamina: 73 }, sockets: { red: 1, yellow: 1, blue: 1 } },
  33517: { name: 'Bonefist Gauntlets', slot: 'hands', stats: { armor: 1005, hitRating: 21, parryRating: 30, stamina: 51 }, sockets: { red: 1, blue: 1 } },
  33523: { name: 'Sabatons of the Righteous Defender', slot: 'feet', stats: { armor: 1105, blockValue: 30, defenseRating: 18, spellDamage: 23, spellHitRating: 18, stamina: 45 }, sockets: { red: 1, blue: 1 } },
  33524: { name: 'Girdle of the Protector', slot: 'waist', stats: { armor: 904, defenseRating: 11, dodgeRating: 27, spellDamage: 23, spellHitRating: 18, stamina: 40 }, sockets: { blue: 1, yellow: 1 } },
  33593: { name: 'Slikk\'s Cloak of Placation', slot: 'back', stats: { armor: 346, defenseRating: 16, dodgeRating: 25, stamina: 37 } },
  33687: { name: 'Vengeful Gladiator\'s Gavel', slot: 'weapon', stats: { intellect: 20, resilienceRating: 18, spellDamage: 247, spellHitRating: 17, stamina: 30 } },
  33695: { name: 'Vengeful Gladiator\'s Lamellar Chestpiece', slot: 'chest', stats: { armor: 1825, intellect: 31, resilienceRating: 31, spellCritRating: 38, spellDamage: 30, stamina: 64 }, sockets: { red: 2, yellow: 1 } },
  33698: { name: 'Vengeful Gladiator\'s Lamellar Legguards', slot: 'legs', stats: { armor: 1597, intellect: 29, resilienceRating: 35, spellCritRating: 39, spellDamage: 47, stamina: 70 } },
  33889: { name: 'Vindicator\'s Lamellar Bracers', slot: 'wrist', stats: { armor: 772, intellect: 17, resilienceRating: 15, spellCritRating: 20, spellDamage: 27, stamina: 29 }, sockets: { yellow: 1 } },
  33921: { name: 'Vindicator\'s Pendant of Dominance', slot: 'neck', stats: { intellect: 20, resilienceRating: 18, spellDamage: 30, stamina: 35 }, sockets: { yellow: 1 } },
  34009: { name: 'Hammer of Judgement', slot: 'weapon', stats: { intellect: 22, spellDamage: 236, spellHitRating: 22, stamina: 33 } },
  34010: { name: 'Pepe\'s Shroud of Pacification', slot: 'back', stats: { armor: 118, dodgeRating: 30, hitRating: 25, stamina: 45 } },
  34167: { name: 'Legplates of the Holy Juggernaut', slot: 'legs', stats: { armor: 1735, intellect: 41, spellCritRating: 37, spellDamage: 33, stamina: 49 }, sockets: { red: 1, yellow: 1, blue: 1 } },
  34176: { name: 'Reign of Misery', slot: 'weapon', stats: { intellect: 25, spellDamage: 266, stamina: 24 } },
  34178: { name: 'Collar of the Pit Lord', slot: 'neck', stats: { defenseRating: 25, expertiseRating: 29, stamina: 63 } },
  34185: { name: 'Sword Breaker\'s Bulwark', slot: 'offhand', stats: { armor: 6459, blockValue: 225, blockRating: 16, defenseRating: 20, stamina: 49 }, sockets: { red: 1 } },
  34190: { name: 'Crimson Paragon\'s Cover', slot: 'back', stats: { armor: 129, dodgeRating: 28, expertiseRating: 28, stamina: 61 } },
  34192: { name: 'Pauldrons of Perseverance', slot: 'shoulder', stats: { armor: 1487, blockValue: 68, blockRating: 32, defenseRating: 27, stamina: 60 }, sockets: { yellow: 1, blue: 1 } },
  34193: { name: 'Spaulders of the Thalassian Savior', slot: 'shoulder', stats: { armor: 1487, intellect: 25, spellCritRating: 22, spellDamage: 33, stamina: 28 }, sockets: { blue: 1, yellow: 1 } },
  34213: { name: 'Ring of Hardened Resolve', slot: 'ring', stats: { armor: 308, blockValue: 42, defenseRating: 32, expertiseRating: 22, stamina: 48 } },
  34216: { name: 'Heroic Judicator\'s Chestguard', slot: 'chest', stats: { armor: 1983, defenseRating: 29, dodgeRating: 44, intellect: 22, spellDamage: 60, stamina: 78 }, sockets: { blue: 1, yellow: 2 } },
  34243: { name: 'Helm of Burning Righteousness', slot: 'head', stats: { armor: 1660, intellect: 43, spellCritRating: 34, spellDamage: 46, stamina: 51 }, sockets: { meta: 1, red: 1 } },
  34345: { name: 'Crown of Anasterian', slot: 'head', stats: { armor: 1660, critRating: 40, stamina: 67, strength: 61 }, sockets: { meta: 1, red: 1 } },
  34352: { name: 'Borderland Fortress Grips', slot: 'hands', stats: { armor: 1217, defenseRating: 22, dodgeRating: 36, parryRating: 29, stamina: 66 }, sockets: { red: 1, yellow: 1 } },
  34382: { name: 'Judicator\'s Legguards', slot: 'legs', stats: { armor: 1735, blockValue: 33, defenseRating: 40, dodgeRating: 34, intellect: 22, spellDamage: 47, stamina: 78 }, sockets: { blue: 2, red: 1 } },
  34389: { name: 'Spaulders of the Thalassian Defender', slot: 'shoulder', stats: { armor: 1487, blockValue: 51, defenseRating: 27, intellect: 24, spellDamage: 37, stamina: 60 }, sockets: { red: 1, blue: 1 } },
  34401: { name: 'Helm of Uther\'s Resolve', slot: 'head', stats: { armor: 1611, blockValue: 38, defenseRating: 32, dodgeRating: 41, intellect: 20, spellDamage: 39, stamina: 91 }, sockets: { meta: 1, blue: 1 } },
  34433: { name: 'Lightbringer Wristguards', slot: 'wrist', stats: { armor: 841, blockRating: 15, defenseRating: 20, dodgeRating: 22, spellDamage: 25, stamina: 49 }, sockets: { blue: 1 } },
  34473: { name: 'Commendation of Kael\'thas', slot: 'trinket', stats: { stamina: 57 } },
  34488: { name: 'Lightbringer Waistguard', slot: 'waist', stats: { armor: 1081, blockRating: 20, defenseRating: 28, dodgeRating: 30, spellDamage: 33, stamina: 64 }, sockets: { blue: 1 } },
  34560: { name: 'Lightbringer Stompers', slot: 'feet', stats: { armor: 1322, blockValue: 32, defenseRating: 23, dodgeRating: 30, spellDamage: 22, stamina: 58 }, sockets: { blue: 1 } },
  34888: { name: 'Ring of the Stalwart Protector', slot: 'ring', stats: { armor: 392, dodgeRating: 28, stamina: 45 } },
  34945: { name: 'Shattrath Protectorate\'s Breastplate', slot: 'chest', stats: { armor: 1765, defenseRating: 26, spellDamage: 60, spellHitRating: 34, stamina: 78 }, sockets: { blue: 1 } },
  34947: { name: 'Blue\'s Greaves of the Righteous Guardian', slot: 'feet', stats: { armor: 1213, blockRating: 34, spellDamage: 26, spellHitRating: 23, stamina: 58 }, sockets: { red: 1 } },
  34986: { name: 'Brutal Gladiator\'s Barrier', slot: 'offhand', stats: { armor: 6662, blockValue: 185, intellect: 25, resilienceRating: 27, spellDamage: 40, stamina: 37 } },
  35014: { name: 'Brutal Gladiator\'s Gavel', slot: 'weapon', stats: { intellect: 21, resilienceRating: 18, spellDamage: 266, spellHitRating: 19, stamina: 33 } },
  35094: { name: 'Brutal Gladiator\'s Shield Wall', slot: 'offhand', stats: { armor: 6662, blockValue: 185, resilienceRating: 31, stamina: 67 } },
};
